/*
 * ultrasonic.c
 *
 *  Created on: Oct 29, 2023
 *      Author: Mustafa Taha
 */

#include "ultrasonic.h"
#include "icu.h"
#include "util/delay.h"

/*******************************************************************************
 *                           Global Variables                                  *
 *******************************************************************************/

/* (g_echo_time variable) to store time for high value in echo pin */
static uint16 g_echo_time = 0;


/*******************************************************************************
 *                      Functions Definitions                                  *
 *******************************************************************************
*/

/*
 * Description: function responsible for initialization of ultrasonic
 * 1-initialize ICU
 * 2-Setup the ICU call back function.
 * 3-Setup the direction for the trigger pin as output pin through the GPIO driver
 */
void Ultrasonic_init(void){

	/*  initialize the ICU */
	Icu_ConfigType Config={F_CPU_8,RISING};
	Icu_init(&Config);

	/* set call back function so (ICU driver)lower layer can call it */
	Icu_setCallBack(Ultrasonic_edgeProcessing);


	/*
	 * setup direction of trigger pin as OUTPUT
	 * initialize the pin by set it to LOW
	 */
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN, PIN_OUTPUT);

	GPIO_writePin(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN,LOGIC_LOW);

	/* no need to setup direction of echo pin as Icu_init() do that	 */

}

/*
 * Description : function responsible for Send the Trigger pulse to the ultrasonic
 */
void Ultrasonic_Trigger(void){

	GPIO_writePin(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN,LOGIC_HIGH);

	_delay_us(ULTRASONIC_TRIGGER_PULSE_DURATION);

	GPIO_writePin(ULTRASONIC_TRIGGER_PORT, ULTRASONIC_TRIGGER_PIN,LOGIC_LOW);

}


/*
 * Function description: function responsible for reading distance using ultrasonic
 *  1- send the trigger pulse by using Ultrasonic_Trigger function.so ultrasonic start to produce echo pulse
 *	2- Start the measurements by the ICU from this moment.
 *
 *	Return: The measured distance in Centimeter
 */
uint16 Ultrasonic_readDistance(void){

	Ultrasonic_Trigger();
	/*
	 * sound speed in air:
	 * 						 = 340 m/s = 340*100 cm/s = 34000 cm/s
	 * total distance:
	 * 						 = speed * echo time
	 * distance:
	 * 						 = total distance /2 = 34000/2 * echo time
	 * 						 = 17000 * echo time
	 *////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
	 /* Total distance is divided by 2 because signal travels from HC-SR04 to object and returns to the module HC-SR-04.*/
	 ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////

	/*
	 *  we have selected an internal 8MHz oscillator frequency for ATmega16, with Prescaler F_CPU/8 for timer frequency.
	 * Then time to execute 1 instruction is 1 us.So, the timer gets incremented after 1 us time elapse
	 * distance:
						= 17000 x (TIMER value) x 1 x 10^-6 cm
						= 0.017 x (TIMER value) cm
						= (TIMER value) / 58.8 cm or (TIMER value) * 0.017 cm
	 *
	 *
	*/
	return (g_echo_time*0.017);
}

/*
 * Function description:
 * This is the call back function called by the ICU driver,
 * we initialize the call back in Ultrasonic_init()
 * the function used to calculate the high time (pulse time) generated by the ultrasonic sensor
 * */
void Ultrasonic_edgeProcessing(void){

	static uint8 g_edgeCount = 0;

	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */

		Icu_clearTimerValue();

		/* Detect falling edge */
		Icu_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{

		/* Store the High time value */
		g_echo_time = Icu_getInputCaptureValue();
		/* Detect rising edge */
		Icu_setEdgeDetectionType(RISING);


		g_edgeCount=0;
	}

}

